// Secure guest ID generation and validation
// Guest IDs are signed server-side to prevent spoofing

import { createHmac, randomUUID } from 'crypto';

// Use a dedicated secret for guest ID signing
// Falls back to a derived key from service role if not set
const GUEST_SECRET = process.env.GUEST_ID_SECRET ||
  (process.env.SUPABASE_SERVICE_ROLE_KEY
    ? createHmac('sha256', 'guest-id-salt').update(process.env.SUPABASE_SERVICE_ROLE_KEY).digest('hex')
    : null);

/**
 * Generate a cryptographically signed guest ID
 * Format: guest-{uuid}-{signature}
 * The signature ensures guests cannot forge IDs
 */
export function generateGuestId(): string {
  if (!GUEST_SECRET) {
    throw new Error('Guest ID secret not configured');
  }

  const id = randomUUID();
  const timestamp = Date.now().toString(36); // Base36 timestamp for uniqueness
  const payload = `${id}-${timestamp}`;

  const signature = createHmac('sha256', GUEST_SECRET)
    .update(payload)
    .digest('hex')
    .slice(0, 12); // 12 hex chars = 48 bits, sufficient for validation

  return `guest-${payload}-${signature}`;
}

/**
 * Validate a guest ID signature
 * Returns true if the ID was generated by our server
 */
export function validateGuestId(guestId: string | null | undefined): boolean {
  if (!guestId || !GUEST_SECRET) {
    return false;
  }

  // Must start with 'guest-'
  if (!guestId.startsWith('guest-')) {
    return false;
  }

  const parts = guestId.slice(6).split('-'); // Remove 'guest-' prefix

  // Format: uuid (5 parts) + timestamp + signature
  // UUID has 5 parts when split by '-', plus timestamp and signature = 7 parts minimum
  if (parts.length < 7) {
    return false;
  }

  // Extract signature (last part)
  const signature = parts.pop()!;

  // Extract timestamp (second to last)
  const timestamp = parts.pop()!;

  // Remaining parts form the UUID
  const uuid = parts.join('-');

  // Validate UUID format
  const uuidRegex = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
  if (!uuidRegex.test(uuid)) {
    return false;
  }

  // Reconstruct payload and verify signature
  const payload = `${uuid}-${timestamp}`;
  const expectedSignature = createHmac('sha256', GUEST_SECRET)
    .update(payload)
    .digest('hex')
    .slice(0, 12);

  // Constant-time comparison to prevent timing attacks
  if (signature.length !== expectedSignature.length) {
    return false;
  }

  let result = 0;
  for (let i = 0; i < signature.length; i++) {
    result |= signature.charCodeAt(i) ^ expectedSignature.charCodeAt(i);
  }

  return result === 0;
}

/**
 * Extract the UUID portion from a guest ID for storage/lookup
 * Returns null if the guest ID is invalid
 */
export function extractGuestUuid(guestId: string): string | null {
  if (!validateGuestId(guestId)) {
    return null;
  }

  const parts = guestId.slice(6).split('-');
  parts.pop(); // Remove signature
  parts.pop(); // Remove timestamp
  return parts.join('-');
}

/**
 * Check if a user ID is a guest ID (starts with 'guest-')
 */
export function isGuestId(userId: string | null | undefined): boolean {
  return typeof userId === 'string' && userId.startsWith('guest-');
}

/**
 * Get effective user ID from authenticated user or validated guest ID
 * Returns null if neither is valid
 */
export function getEffectiveUserId(
  authenticatedUserId: string | null | undefined,
  guestUserId: string | null | undefined
): string | null {
  // Prefer authenticated user
  if (authenticatedUserId) {
    return authenticatedUserId;
  }

  // Validate and use guest ID
  if (guestUserId && validateGuestId(guestUserId)) {
    return guestUserId;
  }

  return null;
}
