import { describe, expect, it } from 'vitest';
import { createRoomSchema, roomIdSchema } from './schemas';

describe('room ID validation', () => {
  it('accepts base36 room codes generated by the app', () => {
    expect(roomIdSchema.safeParse('zzzzzzzz').success).toBe(true);
    expect(createRoomSchema.safeParse({
      id: 'm7qz9k2p',
      name: 'Launch Jam',
      isPublic: true,
      maxUsers: 6,
      settings: {},
    }).success).toBe(true);
  });

  it('rejects malformed room codes', () => {
    expect(roomIdSchema.safeParse('room-123').success).toBe(false);
    expect(roomIdSchema.safeParse('abcd123!').success).toBe(false);
    expect(roomIdSchema.safeParse('abcd12345').success).toBe(false);
  });
});
